version: v0.5.5-alpha.1

serve:
  public:
    base_url: http://0.0.0.0:4433/
    cors:
      enabled: true
  admin:
    base_url: http://0.0.0.0:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  whitelisted_return_urls:
    - http://localhost:4455/

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: false

    verification:
      enabled: false

    logout:
      after:
        default_browser_return_url: http://localhost:4455/login

    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:4455/registration
      after:
        password:
          hooks:
            -
              hook: session

hashers:
  argon2:
    iterations: 3
    parallelism: 24
    salt_length: 16
    key_length: 32
    memory: 131072

log:
  level: debug
  format: text
  leak_sensitive_values: true


identity:
  default_schema_url: file:///root/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
