---
apiVersion: v1
kind: Service
metadata:
  name: kratos
  namespace: infrastructure
  labels:
    name: kratos
spec:
  ports:
    - port: 4433
      name: public
    - port: 4434
      name: private
  selector:
    name: kratos
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: infrastructure
  labels:
    name: kratos
spec:
  selector:
    matchLabels:
      name: kratos
  replicas: 1
  template:
    metadata:
      labels:
        name: kratos
    spec:
      containers:
      - name: kratos
        image: ezdeploy/kratos:v0.7.1
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: "123456"
        ports:
        - name: public
          containerPort: 4433
        - name: admin
          containerPort: 4434
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
